Unas cosas que tan re piolas
frankdilu/CheLang pull request #8
Opened 2020-07-16 19:26 UTC by GuidoDipietro

Viste andamo al pedo así que pintó

Funcionalidades propuestas que ayudarían mucho para hacer estas cosas _que igual no sirven para nada pero andamo como queremo_:

- Modificar listas (epa, por qué no anda eso?)
- Importar funciones de otros archivos
- Un sort() ponele ya que Python lo tiene, para aprovechar, lleva 2 por 30 pesos
- Un random(), en un país en lo que todo es tan inesperado...

Ta re divertido hacer estas cosas bueno me voy

2020-07-16 22:32 UTC, GuidoDipietro commented on examples/generala.che
> +###### AHORA SI NO SABÉS JUGAR TOMATELÁÁÁ #####
Hay que cambiar esas ÁÁÁ, no anda con eso

2020-07-17 12:01 UTC, francodilu requested changes
Además de los comentarios, printear una explicacion breve en consola cuando se ejecuta, explicando muy basicamente lo que hace el programa. Por ejemplo explicar que se esta jugando a la generala (no explicar qué es la generala) o que se estan buscando numeros primos. Resuelto todo esto, sale el merge.

2020-07-17 12:01 UTC, francodilu commented on examples/generala.che
> +    Cuchame("DALE BOOOOOO, DALE BOOOOKAAAAA")
Diría de poner el print antes del Campora... Porque de repente sale campora y como que no se entiende si fue generala o que, pero si tu intencion fue esa dejala

2020-07-17 12:01 UTC, francodilu commented on examples/generala.che
> +# asies #
Como el código esta hecho para ASCII hay que sacar las tildes. Por convención mas que nada

2020-07-17 12:01 UTC, francodilu commented on examples/interseccion_listas.che
> +
Printearía las listas que se comparan para mas claridad para el usuario. Directamente te tira el result y como que hay que ver el código para entender que listas son las usadas

2020-07-17 12:01 UTC, francodilu commented on examples/numeros_bokita.che
> +Cuchame("todavia eso de operador resto % y longitud de una lista esas cosas viste no")
Actualizar el texto inicial. Mas que nada por lo del operador y el len. Capaz una breve explicacion (a lo argento) de qué es un numero bokita

2020-07-17 12:01 UTC, francodilu commented on examples/primos.che
> +che familiaNumerosa es 100
No lo capearía a 100... Puede ser infinito o a lo sumo un numero tipo 1Mill.

2020-07-17 12:01 UTC, francodilu commented on examples/generala.che
> +che tirada es cubilete()
Capaz poner una opción para tirar denuevo y no tener que abrir el archivo para jugar? Tipo apretar r pa mandarle rosca o cualquier otra para salir

2020-07-17 12:01 UTC, frankdilu commented
PD: MIL Gracias. Sos groso.

2020-07-17 14:25 UTC, GuidoDipietro commented on examples/generala.che
> +    Cuchame("DALE BOOOOOO, DALE BOOOOKAAAAA")
Hecho. Aprovecho para compartir esta joya que sucedió mientras debuggeaba, sin forzarlo:

![image](https://user-images.githubusercontent.com/48221146/87796763-2bf1d880-c820-11ea-8dd0-598f4ee0dc8b.png)

2020-07-17 14:28 UTC, GuidoDipietro commented on examples/interseccion_listas.che
> +
No logro printear listas en una misma línea... Creo que hay un _bichito_ porque hacer algo como

```ATextito([1,2,3]) ma ATextito([6,6,6])```

rompe todo.

Lo dejé como estaba, aclarando que se mire el código (así de paso el usuario se deleita).

Una gran funcionalidad a considerar es el _string formatting_ de Python u otros lenguajes, para hacer cosas como

```
"{} y {}".format(var1, var2)

"%s y %s" % (var1, var2)

f"{var1} y {var2}"
```

2020-07-17 14:29 UTC, GuidoDipietro commented on examples/numeros_bokita.che
> +Cuchame("todavia eso de operador resto % y longitud de una lista esas cosas viste no")
Listooo

2020-07-17 14:29 UTC, GuidoDipietro commented on examples/generala.che
> +che tirada es cubilete()
Ahí le metí eso que sugeriste. Para mandarle rosca toda la tarde

2020-07-17 14:31 UTC, GuidoDipietro commented on examples/generala.che
> +# asies #
Listo, los volé a todos

2020-07-17 14:32 UTC, GuidoDipietro commented on examples/primos.che
> +che familiaNumerosa es 100
Agregué funcionalidad para que el usuario decida el límite.

2020-07-17 14:32 UTC, GuidoDipietro commented
Vuelvo a poner esto acá porque fue maravilloso.

![image](https://user-images.githubusercontent.com/48221146/87797527-2d6fd080-c821-11ea-946b-2e618067174e.png)

Orgullo argentino.

2020-07-17 15:23 UTC, frankdilu commented on examples/interseccion_listas.che
> +
Si... Esta tomando a la funcion como variable y el value es la clase String pero no el valor en si del string... Buen issue, para fixear.

Sobre el string formatting la verdad que creo que se va del alcance del lenguaje... Aparte que soy mas partidario del "string" + variable + "string", que actualmente funciona y me parece suficiente(?

2020-07-17 15:35 UTC, merged

2020-07-17 16:11 UTC, GuidoDipietro commented on examples/interseccion_listas.che
> +
Me parece bien, es medio complejo para implementar